name: Python application

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-linux:
    name: Linux
    strategy: 
      matrix:
        arch: [aarch64, x86_64]

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: execute py script
      run: python pr1.py
