name: Python application

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: execute py script
      run: python pr1.py
  
  test-arm64:
    runs-on: ubuntu-latest
    name: Test on ARM64
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up emulation
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - name: Print Architecture
        uses: docker://multiarch/ubuntu-core:arm64-focal
        with:
          args: 'uname -a'
      
      - name: Test ARM64
        uses: docker://multiarch/ubuntu-core:arm64-focal
        with:
          args: >
            bash -c
            "apt-get update &&
            apt-get install -y python3.8 &&
            python3.8 pr1.py
            "
