name: Python application

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: execute py script
      run: python pr1.py
  
  test-arm64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - cp37-cp37m
          - cp38-cp38
        build-type:
          - "cext"
          - "nocext"

      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up emulation
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Run tests
        uses: docker://quay.io/pypa/manylinux2014_aarch64
        with:
          args: |
            bash -c "
            python pr1.py
            "
